mod string_00;
mod string_01;
mod string_02;
mod string_03;
mod string_04;
mod string_05;
mod string_06;
mod string_07;
mod string_08;
mod linked_list_00;
mod linked_list_01;
mod linked_list_02;
mod linked_list_03;
mod linked_list_04;
mod linked_list_05;
mod linked_list_06;
mod linked_list_07;
mod linked_list_08;
mod stacks_and_queues_00;
mod stacks_and_queues_01;
mod stacks_and_queues_02;
mod stacks_and_queues_03;
mod stacks_and_queues_04;
mod stacks_and_queues_05;
mod trees_and_graphs_00;
mod trees_and_graphs_01;
mod trees_and_graphs_02;
mod trees_and_graphs_03;
mod trees_and_graphs_04;
mod trees_and_graphs_05;
mod trees_and_graphs_06;
mod trees_and_graphs_07;
mod trees_and_graphs_08;
mod recursive_and_dynamic_programming_00;
mod recursive_and_dynamic_programming_01;
mod recursive_and_dynamic_programming_02;
mod recursive_and_dynamic_programming_03;
mod recursive_and_dynamic_programming_04;
mod recursive_and_dynamic_programming_05;
mod recursive_and_dynamic_programming_06;

fn main() {
    //string_00::run();
    //string_01::run();
    //string_02::run();
    //string_03::run();
    //string_04::run();
    //string_05::run();
    //string_06::run();
    string_07::run();
    //string_08::run();
    //linked_list_00::run();
    //linked_list_01::run();
    //linked_list_02::run();
    //linked_list_03::run();
    //linked_list_04::run();
    //linked_list_05::run();
    //linked_list_06::run();
    //linked_list_07::run();
    //linked_list_08::run();
    //stacks_and_queues_00::run();
    //stacks_and_queues_01::run();
    //stacks_and_queues_02::run();
    //stacks_and_queues_03::run();
    //stacks_and_queues_04::run();
    //stacks_and_queues_05::run();
    //trees_and_graphs_00::run();
    //trees_and_graphs_01::run();
    //trees_and_graphs_02::run();
    //trees_and_graphs_03::run();
    //trees_and_graphs_04::run();
    //trees_and_graphs_05::run();
    //trees_and_graphs_06::run();
    //trees_and_graphs_07::run();
    //trees_and_graphs_08::run();
    //recursive_and_dynamic_programming_00::run();
    //recursive_and_dynamic_programming_01::run();
    //recursive_and_dynamic_programming_02::run();
    //recursive_and_dynamic_programming_03::run();
    //recursive_and_dynamic_programming_04::run();
    //recursive_and_dynamic_programming_05::run();
    //recursive_and_dynamic_programming_06::run();
}
